name: My First Workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Prints Welcome Message
          run: echo "Welcome"
        - name: List Files
          run: ls
        - name: Read file
          run: cat README.md
        - name: Create file
          run: touch test.txt
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with: 
            name: Test File
            path: test.txt

          